### ISSUE TITLE
Script per il nuovo ebook-reader della zanichelli

### ISSUE THREAD

**Issue by ilCime** [Bbalduzz/Booktab-PDF-Downloader#2]
Ciao, sto trovando i tuoi script molto utili per accedere al mio materiale scolastico però alcuni dei miei testi si trovano sulla piattaforma "laZebook", per caso sai se questo script si può riciclare? Grazie.

**Comment by Bbalduzz** [comment]
ciao! grazie mille per il feedback.
Per laZebook puoi usare questo script: [https://github.com/Bbalduzz/Kitaboo-PDF-Downloader](https://github.com/Bbalduzz/Kitaboo-PDF-Downloader)
